debug: false
uuid: e4c16403-17a9-4772-9b75-0d81a3f86b4a
token_id: y4fDfKtPTgoEAEEw
token: YUhvJcIXiM8S8waJdwt8Mj9dwD6ZKPHt5OuzUdIg7iJ13La4Bh9nvQRxB8qsYUsK
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: true
    cert: /etc/cert/fullchain.pem
    key: /etc/cert/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/Jexactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://skyshomepanel.jcbm-mc.uk'
